diff decoded/A00.data.mine input/A00.data
diff decoded/A01.data.mine input/A01.data
diff decoded/A02.data.mine input/A02.data
diff decoded/A03.data.mine input/A03.data
diff decoded/A04.data.mine input/A04.data
diff decoded/A05.data.mine input/A05.data
diff decoded/A06.data.mine input/A06.data
diff decoded/A07.data.mine input/A07.data
diff decoded/A08.data.mine input/A08.data
diff decoded/A09.data.mine input/A09.data
diff decoded/A10.data.mine input/A10.data
diff decoded/A11.data.mine input/A11.data
diff decoded/A12.data.mine input/A12.data
diff decoded/A13.data.mine input/A13.data
diff decoded/A14.data.mine input/A14.data
diff decoded/A15.data.mine input/A15.data
diff decoded/A16.data.mine input/A16.data
diff decoded/A17.data.mine input/A17.data
diff decoded/A18.data.mine input/A18.data
diff decoded/A19.data.mine input/A19.data
diff decoded/A20.data.mine input/A20.data
diff decoded/A21.data.mine input/A21.data
diff decoded/A22.data.mine input/A22.data
diff decoded/A23.data.mine input/A23.data
diff decoded/A24.data.mine input/A24.data
diff decoded/A25.data.mine input/A25.data
diff decoded/A26.data.mine input/A26.data
diff decoded/A27.data.mine input/A27.data
diff decoded/A28.data.mine input/A28.data
diff decoded/A29.data.mine input/A29.data
diff decoded/A30.data.mine input/A30.data
diff decoded/A31.data.mine input/A31.data
diff decoded/A32.data.mine input/A32.data
diff decoded/A33.data.mine input/A33.data
diff decoded/A34.data.mine input/A34.data
diff decoded/A35.data.mine input/A35.data
diff decoded/A36.data.mine input/A36.data
diff decoded/A37.data.mine input/A37.data
diff decoded/A38.data.mine input/A38.data
diff decoded/A39.data.mine input/A39.data
diff decoded/A40.data.mine input/A40.data
diff decoded/A41.data.mine input/A41.data
diff decoded/A42.data.mine input/A42.data
diff decoded/A43.data.mine input/A43.data
diff decoded/A44.data.mine input/A44.data
diff decoded/A45.data.mine input/A45.data
diff decoded/A46.data.mine input/A46.data
diff decoded/A47.data.mine input/A47.data
diff decoded/A48.data.mine input/A48.data
diff decoded/A49.data.mine input/A49.data
diff decoded/A50.data.mine input/A50.data
diff decoded/A51.data.mine input/A51.data
diff decoded/A52.data.mine input/A52.data
diff decoded/A53.data.mine input/A53.data
diff decoded/A54.data.mine input/A54.data
diff decoded/A55.data.mine input/A55.data
diff decoded/A56.data.mine input/A56.data
diff decoded/A57.data.mine input/A57.data
diff decoded/A58.data.mine input/A58.data
diff decoded/A59.data.mine input/A59.data
